ALTER TABLE "AgentRun" ADD COLUMN "modelRequestCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AgentRun" ADD COLUMN "modelRequestLimit" INTEGER NOT NULL DEFAULT 12;

ALTER TABLE "AgentTask" ADD COLUMN "mode" TEXT NOT NULL DEFAULT 'executor';
ALTER TABLE "AgentTask" ADD COLUMN "dependsOn" JSONB;
ALTER TABLE "AgentTask" ADD COLUMN "modelRequestCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AgentTask" ADD COLUMN "modelRequestLimit" INTEGER NOT NULL DEFAULT 8;
