import { CodingAgentId, CodingAgentMetadata } from './types';

export const CODING_AGENTS_REGISTRY: Record<CodingAgentId, CodingAgentMetadata> = {
  pi: {
    id: 'pi',
    name: 'Pi Coding Agent',
    provider: 'Pi / Earendil',
    command: 'pi',
    packageName: '@earendil-works/pi-coding-agent',
    description: '本地原生集成的轻量交互式编码智能体，支持工具扩展与自动化代码生成。',
    isBuiltin: true,
    versionArgs: ['-v'],
    installCommand: 'npm install @earendil-works/pi-coding-agent',
  },
  'claude-code': {
    id: 'claude-code',
    name: 'Claude Code',
    provider: 'Anthropic',
    command: 'claude',
    packageName: '@anthropic-ai/claude-code',
    description: 'Anthropic 官方研究级终端编码智能体，具备深度代码库推理与重构能力。',
    isBuiltin: false,
    versionArgs: ['--version'],
    installCommand: 'npm install -g @anthropic-ai/claude-code',
  },
  codex: {
    id: 'codex',
    name: 'OpenAI Codex',
    provider: 'OpenAI',
    command: 'codex',
    packageName: '@openai/codex',
    description: 'OpenAI 体系交互式代码与指令执行工具。',
    isBuiltin: false,
    versionArgs: ['--version'],
    installCommand: 'npm install -g @openai/codex',
  },
  dsh: {
    id: 'dsh',
    name: 'DeepSeek Harness',
    provider: 'DeepSeek',
    command: 'dsh',
    packageName: '@deepseek-ai/dsh',
    description: 'DeepSeek 深度优化的高效代码生成与多轮任务测试工具。',
    isBuiltin: false,
    versionArgs: ['--version'],
    installCommand: 'npm install -g @deepseek-ai/dsh',
  },
  opencode: {
    id: 'opencode',
    name: 'OpenCode',
    provider: 'OpenCode',
    command: 'opencode',
    packageName: 'opencode-ai',
    description: '开放式多模型代码生成与工作区辅助 CLI。',
    isBuiltin: false,
    versionArgs: ['--version'],
    installCommand: 'npm install -g opencode-ai',
  },
  grok: {
    id: 'grok',
    name: 'Grok CLI',
    provider: 'xAI',
    command: 'grok',
    packageName: '@xai-official/grok',
    description: 'xAI Grok 编程与系统推理终端套件。',
    isBuiltin: false,
    versionArgs: ['--version'],
    installCommand: 'npm install -g @xai-official/grok',
  },
};

export const SUPPORTED_AGENT_IDS: CodingAgentId[] = [
  'pi',
  'claude-code',
  'codex',
  'dsh',
  'opencode',
  'grok',
];
