ALTER TABLE "User" ADD COLUMN "imageModelEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "imageModelName" TEXT;
ALTER TABLE "User" ADD COLUMN "imageModelSize" TEXT DEFAULT '1024x1024';
