import type { TrendingCategory, TrendingSourceConfig } from './types';

const DAILYHOT_BASE = process.env.DAILYHOT_API_BASE || 'https://dailyhotapi-livid.vercel.app';

export const TRENDING_CATEGORIES: { id: TrendingCategory | 'all'; name: string; icon: string }[] = [
  { id: 'all', name: '全网热榜', icon: '🔥' },
  { id: 'hot', name: '全民热议', icon: '⚡' },
  { id: 'anime', name: '二次元游戏', icon: '🎮' },
  { id: 'tech', name: '科技商业', icon: '💡' },
  { id: 'dev', name: '数码极客', icon: '💻' },
  { id: 'culture', name: '文化生活', icon: '🎬' },
  { id: 'crypto', name: '加密Web3', icon: '🪙' },
];

export const TRENDING_SOURCES: TrendingSourceConfig[] = [
  // 1. 全民热议 (7 个)
  {
    id: 'zhihu',
    name: '知乎热榜',
    category: 'hot',
    categoryName: '全民热议',
    icon: '🔮',
    url: 'https://api.zhihu.com/topstory/hot-lists/total?limit=50',
    type: 'zhihu',
    description: '知乎全站实时热点问答，适合深度思考与多视角辩论',
    enabled: true,
  },
  {
    id: 'weibo',
    name: '微博热搜',
    category: 'hot',
    categoryName: '全民热议',
    icon: '🔥',
    url: 'https://api.98dou.cn/api/hotlist?type=weibo',
    type: 'weibo',
    description: '文娱、突发新闻与大众舆情，适合吃瓜吐槽与生活破冰',
    enabled: true,
  },
  {
    id: 'baidu',
    name: '百度热搜',
    category: 'hot',
    categoryName: '全民热议',
    icon: '🔍',
    url: 'https://top.baidu.com/api/board?platform=wise&tab=realtime',
    type: 'baidu',
    description: '全网全民关注的社会民生大事件，适合大局热点速览',
    enabled: true,
  },
  {
    id: 'toutiao',
    name: '今日头条',
    category: 'hot',
    categoryName: '全民热议',
    icon: '📰',
    url: 'https://api.98dou.cn/api/hotlist?type=toutiao',
    type: 'toutiao',
    description: '全国大事件与热点资讯，覆盖时政民生与热搜头条',
    enabled: true,
  },
  {
    id: 'thepaper',
    name: '澎湃新闻',
    category: 'hot',
    categoryName: '全民热议',
    icon: '🗞️',
    url: `${DAILYHOT_BASE}/thepaper`,
    type: 'dailyhot',
    description: '专注深度报道与时政思想，严肃新闻权威发声',
    enabled: true,
  },
  {
    id: 'qq-news',
    name: '腾讯新闻',
    category: 'hot',
    categoryName: '全民热议',
    icon: '🐧',
    url: `${DAILYHOT_BASE}/qq-news`,
    type: 'dailyhot',
    description: '腾讯新闻热点要闻与焦点资讯',
    enabled: true,
  },
  {
    id: 'netease-news',
    name: '网易新闻',
    category: 'hot',
    categoryName: '全民热议',
    icon: '🔴',
    url: `${DAILYHOT_BASE}/netease-news`,
    type: 'dailyhot',
    description: '网易新闻热点聚焦与犀利跟帖文化',
    enabled: true,
  },

  // 2. 二次元与游戏 (5 个)
  {
    id: 'bilibili',
    name: 'B站热门',
    category: 'anime',
    categoryName: '二次元游戏',
    icon: '📺',
    url: 'https://api.bilibili.com/x/web-interface/popular?ps=20&pn=1',
    type: 'bilibili',
    description: '年轻人流行文化、二次元、梗文化热门，适合日常闲聊与趣味互动',
    enabled: true,
  },
  {
    id: 'genshin',
    name: '原神热点',
    category: 'anime',
    categoryName: '二次元游戏',
    icon: '⚔️',
    url: `${DAILYHOT_BASE}/genshin`,
    type: 'dailyhot',
    description: '提瓦特大世界资讯、角色前瞻与活动讨论',
    enabled: true,
  },
  {
    id: 'hupu',
    name: '虎扑步行街',
    category: 'anime',
    categoryName: '二次元游戏',
    icon: '🏀',
    url: `${DAILYHOT_BASE}/hupu`,
    type: 'dailyhot',
    description: '体育竞技、直男街薪日常与爆笑直球吐槽',
    enabled: true,
  },
  {
    id: 'tieba',
    name: '百度贴吧',
    category: 'anime',
    categoryName: '二次元游戏',
    icon: '💬',
    url: `${DAILYHOT_BASE}/tieba`,
    type: 'dailyhot',
    description: '中文互联网草根文化、神帖与网络热梗发源地',
    enabled: true,
  },
  {
    id: 'acfun',
    name: 'A站文章',
    category: 'anime',
    categoryName: '二次元游戏',
    icon: '🐒',
    url: `${DAILYHOT_BASE}/acfun`,
    type: 'dailyhot',
    description: 'AcFun 猴山老二次元弹幕与硬核日常讨论',
    enabled: true,
  },

  // 3. 科技商业 (3 个)
  {
    id: '36kr',
    name: '36氪快讯',
    category: 'tech',
    categoryName: '科技商业',
    icon: '⚡',
    url: 'https://gateway.36kr.com/api/mis/nav/newsflash/flow',
    type: '36kr',
    description: '创投、商业模式、科技前沿动态，适合行业洞察与商业策划',
    enabled: true,
  },
  {
    id: 'sspai',
    name: '少数派',
    category: 'tech',
    categoryName: '科技商业',
    icon: '📱',
    url: `${DAILYHOT_BASE}/sspai`,
    type: 'dailyhot',
    description: '高效数字生活、软硬件体验与效率工具指南',
    enabled: true,
  },
  {
    id: 'ifanr',
    name: '爱范儿',
    category: 'tech',
    categoryName: '科技商业',
    icon: '💡',
    url: `${DAILYHOT_BASE}/ifanr`,
    type: 'dailyhot',
    description: '报道未来生活方式，关注潮科技、前沿硬件与设计美学',
    enabled: true,
  },

  // 4. 数码极客 (4 个)
  {
    id: 'ithome',
    name: 'IT之家',
    category: 'dev',
    categoryName: '数码极客',
    icon: '💻',
    url: `${DAILYHOT_BASE}/ithome`,
    type: 'dailyhot',
    description: '数码硬件、操作系统与IT业界最前线爆料',
    enabled: true,
  },
  {
    id: 'juejin',
    name: '掘金热榜',
    category: 'dev',
    categoryName: '数码极客',
    icon: '💎',
    url: `${DAILYHOT_BASE}/juejin`,
    type: 'dailyhot',
    description: '开发者技术干货、架构实践与开源项目分享',
    enabled: true,
  },
  {
    id: 'hellogithub',
    name: 'HelloGitHub',
    category: 'dev',
    categoryName: '数码极客',
    icon: '🐙',
    url: `${DAILYHOT_BASE}/hellogithub`,
    type: 'dailyhot',
    description: '有趣、入门级开源项目月刊与全球开发者趋势',
    enabled: true,
  },
  {
    id: 'csdn',
    name: 'CSDN热榜',
    category: 'dev',
    categoryName: '数码极客',
    icon: '📚',
    url: `${DAILYHOT_BASE}/csdn`,
    type: 'dailyhot',
    description: '中文技术社区算法、AI、后端架构热门文章',
    enabled: true,
  },

  // 5. 文化生活 (2 个)
  {
    id: 'douban-movie',
    name: '豆瓣电影',
    category: 'culture',
    categoryName: '文化生活',
    icon: '🎬',
    url: `${DAILYHOT_BASE}/douban-movie`,
    type: 'dailyhot',
    description: '院线新片评分、影迷口碑与高分榜单',
    enabled: true,
  },
  {
    id: 'weread',
    name: '微信读书',
    category: 'culture',
    categoryName: '文化生活',
    icon: '📖',
    url: `${DAILYHOT_BASE}/weread`,
    type: 'dailyhot',
    description: '热门飙升书籍、全网阅读指数与深度书单推荐',
    enabled: true,
  },

  // 6. 加密Web3 (4 个)
  {
    id: 'binance',
    name: '币安资讯',
    category: 'crypto',
    categoryName: '加密Web3',
    icon: '🟡',
    url: 'https://www.binance.com/bapi/composite/v1/public/cms/article/catalog/list/query?catalogId=48&pageNo=1&pageSize=20',
    type: 'binance',
    description: '全球最大交易所新币上线、合约重大动向与官方要闻',
    enabled: false,
  },
  {
    id: 'blockbeats',
    name: '律动 BlockBeats',
    category: 'crypto',
    categoryName: '加密Web3',
    icon: '⚡',
    url: 'https://www.theblockbeats.info/newsflash',
    type: 'blockbeats',
    description: '中文 Web3 第一快讯与深度研报门户，覆盖独家首发、融资与行情要闻',
    enabled: true,
  },
  {
    id: 'foresight',
    name: 'Foresight News',
    category: 'crypto',
    categoryName: '加密Web3',
    icon: '🔭',
    url: 'https://foresightnews.pro/news',
    type: 'foresight',
    description: '权威中文 Web3 行业要闻、研报与数据追踪，高信噪比一手快讯',
    enabled: true,
  },
  {
    id: 'okx',
    name: '欧易星球热议',
    category: 'crypto',
    categoryName: '加密Web3',
    icon: '🪐',
    url: 'https://www.okx.com/zh-hans/orbit/topics',
    type: 'okx',
    description: '欧易OKX星球热门议题、代币洞察、ETF资金动向与Web3大事件',
    enabled: true,
  },
  {
    id: 'cointelegraph',
    name: 'CoinTelegraph',
    category: 'crypto',
    categoryName: '加密Web3',
    icon: '⚡',
    url: 'https://cointelegraph.com/rss',
    type: 'rss',
    description: '全球头号加密货币新闻门户，权威报道宏观政策与链上突发',
    enabled: true,
  },
  {
    id: 'coindesk',
    name: 'CoinDesk',
    category: 'crypto',
    categoryName: '加密Web3',
    icon: '📈',
    url: 'https://www.coindesk.com/arc/outboundfeeds/rss/',
    type: 'rss',
    description: '机构级 Web3 深度智库与比特币、以太坊监管金融要闻',
    enabled: true,
  },
];

export function getSourceConfig(id: string): TrendingSourceConfig | undefined {
  return TRENDING_SOURCES.find((s) => s.id === id);
}

export function getSourcesByCategory(category: TrendingCategory | 'all'): TrendingSourceConfig[] {
  if (category === 'all') return TRENDING_SOURCES.filter((s) => s.enabled !== false);
  return TRENDING_SOURCES.filter((s) => s.enabled !== false && s.category === category);
}
